apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: kinetic-backend
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://18.209.57.159"
  QUEUE_CONNECTION: "database"
  SESSION_DRIVER: "file" # changing to array for API
  CACHE_STORE: "file"
  # Add other non-secret config here
