apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: kinetic-backend
type: Opaque

stringData:
  APP_KEY: "base64:GHGzKBd7QK+YY++f//SBpDR5wI7qjBhPsQ28+wVBVk0="

  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres.omtdxojcsgexfevyoypb"
  DB_PORT: "5432"
  DB_DATABASE: "kinetic"
  DB_USERNAME: "postgres.omtdxojcsgexfevyoypb"
  DB_PASSWORD: "akanksh0945"
  DB_SSLMODE: "disable"

  SANCTUM_STATEFUL_DOMAINS: "localhost,127.0.0.1"
  SESSION_DOMAIN: "localhost"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "your_email@gmail.com"
  MAIL_PASSWORD: "your_app_password"
  MAIL_FROM_ADDRESS: "your_email@gmail.com"
  MAIL_FROM_NAME: "Kinetic"