apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: kinetic-backend
type: Opaque
data:
  APP_KEY: <base64-app-key>
  DB_CONNECTION: cGdzcWw=
  DB_HOST: <base64-db-host>
  DB_PORT: NTQzMg==
  DB_DATABASE: <base64-db-name>
  DB_USERNAME: <base64-db-user>
  DB_PASSWORD: <base64-db-pass>
  SANCTUM_STATEFUL_DOMAINS: <base64-domains>
  SESSION_DOMAIN: <base64-session-domain>
  MAIL_MAILER: <base64-mail-mailer>
  MAIL_HOST: <base64-mail-host>
  MAIL_PORT: <base64-mail-port>
  MAIL_USERNAME: <base64-mail-user>
  MAIL_PASSWORD: <base64-mail-pass>
  MAIL_FROM_ADDRESS: <base64-mail-from>
  MAIL_FROM_NAME: <base64-mail-from-name>
