apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: kinetic-backend
type: Opaque

stringData:
  APP_KEY: "base64:CHANGE_ME"

  DB_CONNECTION: "pgsql"
  DB_HOST: "CHANGE_ME"
  DB_PORT: "5432"
  DB_DATABASE: "CHANGE_ME"
  DB_USERNAME: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  DB_SSLMODE: "require"

  SANCTUM_STATEFUL_DOMAINS: "localhost,127.0.0.1"
  SESSION_DOMAIN: "localhost"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "CHANGE_ME"
  MAIL_PASSWORD: "CHANGE_ME"
  MAIL_FROM_ADDRESS: "CHANGE_ME"
  MAIL_FROM_NAME: "Kinetic"