apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-email
  namespace: kinetic-backend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: backend-email
  template:
    metadata:
      labels:
        app: backend-email
    spec:
      priorityClassName: low-priority

      nodeSelector:
        app-worker: "true"

      containers:
        - name: email
          image: akankshrakesh/kinetic-backend:${BUILD_NUMBER}
          command: ["php", "artisan", "queue:work", "--queue=emails"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              cpu: "20m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"
