apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: kinetic-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
      http:
        paths:
          - pathType: Prefix
            path: /api/(.*)
            backend:
              service:
                name: backend-general
                port:
                  number: 8080
          - pathType: Prefix
            path: /auth/(.*)
            backend:
              service:
                name: backend-auth
                port:
                  number: 8080
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: backend-general
                port:
                  number: 8080
