apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: kinetic-backend
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:

      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: backend-auth
            port:
              number: 8080

      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-general
            port:
              number: 8080

      - path: /sanctum
        pathType: Prefix
        backend:
          service:
            name: backend-auth
            port:
              number: 8080