apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: kinetic-backend
data:
  APP_NAME: Kinetic
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://localhost
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_DATABASE: kinetic
  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"
  CACHE_STORE: database
  QUEUE_CONNECTION: database
  SANCTUM_STATEFUL_DOMAINS: localhost:3000,127.0.0.1:3000,localhost:8080,127.0.0.1:8080
  CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
