apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: kinetic-backend
type: Opaque
stringData:
  APP_KEY: "base64:GHGzKBd7QK+YY++f//SBpDR5wI7qjBhPsQ28+wVBVk0="
  DB_USERNAME: "postgres.omtdxojcsgexfevyoypb"
  DB_PASSWORD: "akanksh0945"
  DB_SSLMODE: "disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: kinetic-backend
type: Opaque
stringData:
  POSTGRES_DB: "kinetic"
  POSTGRES_USER: "postgres.omtdxojcsgexfevyoypb"
  POSTGRES_PASSWORD: "akanksh0945"
